global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#data-quality-alerts'
    send_resolved: true
    icon_emoji: ':warning:'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Started:* {{ .StartsAt | since }}
      {{ end }}